# Generated by Django 4.1 on 2022-08-30 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0002_flashcards'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flashcards',
            options={'verbose_name_plural': 'flashcards'},
        ),
        migrations.AlterField(
            model_name='flashcards',
            name='title',
            field=models.CharField(max_length=250),
        ),
    ]
