# Generated by Django 4.1 on 2022-09-01 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0004_deck_flashcards_deck'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flashcards',
            name='deck',
        ),
        migrations.AddField(
            model_name='flashcards',
            name='category',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.DeleteModel(
            name='Deck',
        ),
    ]
